---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: nse-sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    containers:
      - name: sidecar
        image: gwtester/nse:0.0.1
        resources:
          limits:
            networkservicemesh.io/socket: 1
        volumeMounts:
          - name: nsm-endpoints
            mountPath: /etc/nsminfo
    volumes:
      - name: nsm-endpoints
        downwardAPI:
          items:
            - path: endpoints
              fieldRef:
                fieldPath: metadata.annotations['ns.networkservicemesh.io/endpoints']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nse-sidecar-injector-webhook-deployment
  labels:
    app: sidecar-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar-injector
  template:
    metadata:
      labels:
        app: sidecar-injector
    spec:
      containers:
        - name: sidecar-injector
          image: gwtester/nse-sidecar-injector:0.0.1
          env:
            - name: LOG_LEVEL
              value: info
          args:
            - --sidecarcfg
            - /etc/webhook/config/sidecarconfig.yaml
            - --tlscert
            - /etc/webhook/certs/cert.pem
            - --tlskey
            - /etc/webhook/certs/key.pem
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
      volumes:
        - name: webhook-certs
          secret:
            secretName: nse-sidecar-injector-webhook-certs
        - name: webhook-config
          configMap:
            name: nse-sidecar-injector-webhook-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: nse-sidecar-injector-webhook-svc
  labels:
    app: sidecar-injector
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: sidecar-injector
